#include "lib.h"

#include "milk_products.h"
#include "meat_products.h"
#include "fish_products.h"
#include "vegetables.h"
#include "fruits.h"
#include "groceries.h"
#include "bakery.h"
#include "frozen_foods.h"
#include "non-alcoholic_beverages.h"
#include "alcoholic_beverages.h"
#include "tea_and_coffee.h"
#include "pets_foods.h"